service: ip2-api
frameworkVersion: '2'

custom:
    imageUploadBucket: ip2-api-dev

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: '20201221'
    iamRoleStatements:
      - Effect: Allow
        Action:
                - s3:*
        Resource: 
                - 'arn:aws:s3:::ip2-api-dev'
                - 'arn:aws:s3:::ip2-api-dev/*'

functions:
    api:
        handler: handler.handler
        events:
        - httpApi: '*'
