service: ip2-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
iamRoleStatements:  
  - Effect: 'Allow'
    Action:
      - 's3:*'
      - "ssm:GetParameter*"
      - 's3:GetObject'
      - 's3:PutObject'
      - 's3:ListObject'
      - 's3:CreateBucket'
    Resource:
      - "arn:aws:s3:::my_bucket/*"
      - "arn:aws:s3:::my_bucket"
      - "arn:aws:s3:::*"
      - "*"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
