service: ip2-api
frameworkVersion: '2'

custom:
    imageUploadBucket: ip2-api-dev

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: '20201221'
    iamRoleStatements:
      - Effect: Allow
        Action:
                - s3:*
        Resource: 
                - '*'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
